### ISSUE TITLE
Product request: add porting for Vybrid VF61

### ISSUE THREAD

**Issue by escherstair** [NXPmicro/rpmsg-lite#1]
I see that rpmsg-lite has been ported to imx6sx_m4, imx7d_m4, lpc5410x and lpc5411x.
Could you port it to m4 core of Vybrid VF61 chip, please?

**Comment by MarekNovakNXP** [comment]
Hello,
Thank you for your interest in RPMsg-Lite!
What is your target board for VF61? I am not sure, when I would be capable of preparing the port, but I can help you in porting. Feel free to ask for any advice. Basically, you need to create your rpmsg_platform.c file. You can use port for i.MX as a template. Then, if you plan to use other environment than FreeRTOS or BM, you need also to port this.
Any patches/pull requests are welcome!

Regards,
Marek

**Comment by escherstair** [comment]
My target is Colibri VF61 module by Toradex.
This implementation seems nice because it's lightweight and because it's from NXP.
I think it's better to have a working component from NXP more than have a lot of different implementations from third parties.

**Comment by escherstair** [comment]
Trying to port RPMsg-Lite to Toradex Colibri VF61 board I noticed one big difference.
Port for i.MX relies on MU (Message Unit), but as far as I understand, VF61 doesn't have it (or it's called in a different way).
Could you help clarifying, please?

**Comment by MarekNovakNXP** [comment]
Hello,
You are right. You will need to replace usage of MU by selecting a word in the shared memory and then you can use the intercore interrupts to notify something new got writtten there and should be consumed by the other core. You will basically need to reserve 2 words in the shared memory - one for the actual content and one for some signaling (data ready, data consumed..) so that you don't overwrite the old message before it is consumed. In i.MX MU it is handled by the MU hardware, but it can be quite easily done in software this way... 

Please, download this release package < 1. goto: https://www.nxp.com/pages/mqx-releases-and-patches:MQXSWDW?fsrch=1&sr=1&pageNum=1 2. login, click on Download button, 3. Select MQX RTOS 4.2, 4. Agree with the licence, Download... > and search for function mcc_triger_cpu_to_cpu_interrupt (Freescale_MQX_4_2\mcc\source\mcc_vf600.c). It will show you how to trigger and intercore interrupt. The register, which are used for this are documented also in the reference manual, but looking at the actual code might help you as well.

Feel free to contact us here in case of any issue,
Regards,
Marek
